EPOCHS: 10
BATCH_SIZE: 8
LAYER_NUMBER: 1
TRAIN_SPLIT: 0.8
RETINA_MODEL: "cnn_2"
IMAGE_SIZE: 512
DEBUG: False
IMAGES_FRACTION: 1.0
CONTINUE_TRAINING: False
SAVED_MODEL_PATH: ""
MODEL_NAME: ""
SAVE_EVERY: 1
