EPOCHS: 100
BATCH_SIZE: 128
CONNECTOME_LAYER_NUMBER: 3
TRAIN_SPLIT: 0.8
RETINA_MODEL: "cnn_2"
IMAGE_SIZE: 512
LEARNING_RATE: 0.0003
DEBUG: False
IMAGES_FRACTION: 1.0
CONTINUE_TRAINING: False
SAVED_MODEL_PATH: "models/long_training_cnn_1_2_layers/epochs_60.pth"
SAVED_MODEL_NAME: "afterbug"
SAVE_EVERY: 10
WANDB: True
PLOT_WEBER_FRACTION: True