EPOCHS: 100
BATCH_SIZE: 128
CONNECTOME_LAYER_NUMBER: 3
TRAIN_SPLIT: 0.8
RETINA_MODEL: "cnn_2"
IMAGE_SIZE: 512
LEARNING_RATE: 0.0001
DEBUG: False
IMAGES_FRACTION: 1.0
CONTINUE_TRAINING: False
SAVED_MODEL_PATH: "models/afterbug_cnn_2_3_layers/epochs_50.pth"
SAVED_MODEL_NAME: "afterbug"
SAVE_EVERY: 10
WANDB: True
PLOT_WEBER_FRACTION: True
TRAIN_IMAGES_DIR: "images/easy_images"
VALIDATION_IMAGES_DIR: "images/easyval_images"